### ISSUE TITLE
Permission Denied with lib/linux_input/generated/* 

### ISSUE THREAD

**Issue by iberianpig** [christopheraue/ruby-linux_input#1]
When I installed linux_input using sudo, there were some files with "600" permissions.

```
$ ls -l /var/lib/gems/2.5.0/gems/linux_input-1.1.0/lib/linux_input/generated/
drwxr-xr-x 2 root root 4.0K  3月 25 10:33 ./
drwxr-xr-x 3 root root 4.0K  3月 25 10:33 ../
-rw------- 1 root root  19K  3月 25 10:33 input.rb
-rw------- 1 root root  539  3月 25 10:33 ioctl.rb
```

So, when ruby calls `require 'linux_input'`, it fails with a permission error.

Could you change permissions of `lib/linux_input/generated/*` to `644`?

## install and check permissions
```shell
$ sudo gem install linux_input
Fetching linux_input-1.1.0.gem
Successfully installed linux_input-1.1.0
Building YARD (yri) index for linux_input-1.1.0...
Done installing documentation for linux_input after 0 seconds
1 gem installed

$ tree -p /var/lib/gems/2.5.0/gems/linux_input-1.1.0/
/var/lib/gems/2.5.0/gems/linux_input-1.1.0/
├── [-rw-r--r--]  Gemfile
├── [-rw-r--r--]  LICENSE.txt
├── [-rw-r--r--]  README.md
├── [-rw-r--r--]  Rakefile
├── [drwxr-xr-x]  lib
│   ├── [drwxr-xr-x]  linux_input
│   │   ├── [drwxr-xr-x]  generated
│   │   │   ├── [-rw-------]  input.rb
│   │   │   └── [-rw-------]  ioctl.rb
│   │   ├── [-rw-r--r--]  input.rb
│   │   ├── [-rw-r--r--]  ioctl.rb
│   │   └── [-rw-r--r--]  version.rb
│   └── [-rw-r--r--]  linux_input.rb
├── [-rw-r--r--]  linux_input.gemspec
├── [drwxr-xr-x]  swig
│   ├── [-rw-r--r--]  input.i
│   └── [-rw-r--r--]  ioctl.i
└── [drwxr-xr-x]  tasks
    └── [-rw-r--r--]  ffi.rake
```

## require linux_input
```shell
[1] pry(main)> require 'linux_input'
Errno::EACCES: Permission denied @ rb_sysopen - /var/lib/gems/2.5.0/gems/linux_input-1.1.0/lib/linux_input/generated/ioctl.rb
from /var/lib/gems/2.5.0/gems/linux_input-1.1.0/lib/linux_input/ioctl.rb:2:in `read'
Caused by LoadError: cannot load such file -- linux_input
from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by christopheraue** [comment]
Thanks for letting me know. Turns out calling `sed -i` during generation of these files did not preserve file permissions. It's fixed now.

I pushed version 1.1.1 of the gem including the fix.
